### ISSUE TITLE
Email setup

### ISSUE THREAD

**Issue by wayangalihpratama** [akvo/isco#127]
- [x] Add german translations to emails https://github.com/akvo/isco/issues/127#issuecomment-1109703480
- [x] When a user registers, send an email to the member admin of the organisation

**Comment by joycarpediem** [comment]
(https://docs.google.com/document/d/1pDC4CvSYA4MBpV1zrGuMPZo_nGxes62uv3qQSlO3Syg/edit)
Priority :
2,1,3

**Comment by joycarpediem** [comment]
add german translation 
[Übersetzung User notification emails -2022.docx](https://github.com/akvo/isco/files/8562886/Ubersetzung.User.notification.emails.-2022.docx)
@wayangalihpratama , the german translations
