### ISSUE TITLE
Filter user list & organisation dropdown by same isco in manage user

### ISSUE THREAD

**Issue by wayangalihpratama** [akvo/isco#186]
- [ ] organisation dropdown filter not working on manage users page
- [ ] check all filter dropdown on manage users

**Comment by joycarpediem** [comment]
@wayangalihpratama , 
Steps : 
I create a user (secretariat admin, staff GISCO)
When this user goes to manage user , the organisation dropdown is not alphabetically sorted
Is the table displaying users with member=GISCO or member contains GISCO ?

**Comment by wayangalihpratama** [comment]
> @wayangalihpratama , Steps : I create a user (secretariat admin, staff GISCO) When this user goes to manage user , the organisation dropdown is not alphabetically sorted Is the table displaying users with member=GISCO or member contains GISCO ?

The table displaying users with members contains GISCO. 
And I'll sort the organisation dropdown value.
