### ISSUE TITLE
Preview survey not working on prod

### ISSUE THREAD

**Issue by wayangalihpratama** [akvo/isco#190]
- [ ] preview function stopped working on the “DISCO 2020 shared Member Survey”

**Comment by wayangalihpratama** [comment]
- This happens because the dependency/skip logic value does not find the option value on the question source (maybe the option use in dependency was deleted)

**Comment by joycarpediem** [comment]
@wayangalihpratama , passed. Move to prod

**Comment by wayangalihpratama** [comment]
> 

What was the error @joycarpediem ?
