### ISSUE TITLE
data download (fine tuning)

### ISSUE THREAD

**Issue by joycarpediem** [akvo/isco#200]
- [x] Once the admin clicks approve, change approve button to a disabled "Approved" button
- [x] In the print instead of showing a concatenated string with organization, submitter, and date of submission, display it in the following format
Member : <Member name>
Submitter : <Submitter name>
Date of submission : <Date>

**Comment by wayangalihpratama** [comment]
- [ ] Download button give blank page to print

**Comment by wayangalihpratama** [comment]
- [ ] Show Request button after approved download request is expired
