### ISSUE TITLE
Create a static configuration for computed validation across multiple questions

### ISSUE THREAD

**Issue by wayangalihpratama** [akvo/isco#278]
A lighter option will be to create this configuration in the backend along with making the provisions to store the configuration . This would entail that once the survey has been setup by the secretariats they indicate to Akvo which set of questions needs these validations . This would mean that only Akvo can configure these validations . If these validations are pre-decided and are not great in number , then this dependence may not be a major bottleneck.

---

**Expected config**
```json
[
  {
    "form_id": 1,
    "validations": [
      {
        "group_id": 1,
        "question_ids": [ 1, 2 ],
        "min": 25
      },
      {
        "group_id": 2,
        "question_ids": [ 3, 4, 5 ],
        "max": 100
      }
    ]
  },
  {
    "form_id": 2,
    "validations": [
      {
        "group_id": 3,
        "question_ids": [ 6, 7 ],
        "max": 100
      }
    ]
  }
]
```

**Comment by joycarpediem** [comment]
Blocked by #317
