### ISSUE TITLE
Test Deactivate questionnaire is not loading

### ISSUE THREAD

**Issue by joycarpediem** [akvo/isco#314]

**Comment by navins94** [comment]
@joycarpediem We don't get to see the form if we don't select Member type 
![Screenshot 2023-02-07 at 12 48 54 PM](https://user-images.githubusercontent.com/24510012/217174753-b0a78a05-73ee-43a5-82d6-5b905652b985.png)

**Comment by joycarpediem** [comment]
@navins94 , the questionnaire is still not loading https://www.loom.com/share/13b64ca26e3f4f32abecbdbc60194f84

**Comment by navins94** [comment]
@joycarpediem Thats different error which is coming from frontend but if you create a new survey with Member type it will load

**Comment by joycarpediem** [comment]
can you log an issue explaining the FE error @navins94

**Comment by navins94** [comment]
@joycarpediem Added

**Comment by navins94** [comment]
@joycarpediem I delete previous question and added new one in the same survey. Now you will be able to see the form in survey
