### ISSUE TITLE
Multiple issues with submission logic

### ISSUE THREAD

**Issue by joycarpediem** [akvo/isco#317]
https://www.loom.com/share/b895d9f034dc4fb0826f99ac2a078719

**Comment by wayangalihpratama** [comment]
- [ ] Check core mandatory question if it setup as cascade and geo question
- [ ] Double check when a survey has computed validation and core mandatory question, make sure that validation come when click submit button

**Comment by wayangalihpratama** [comment]
- Related to [#ARF81](https://github.com/akvo/akvo-react-form/issues/81)

**Comment by dedenbangkit** [comment]
- [ ] Cascade bugs
![isco-cascade-view-bugs](https://user-images.githubusercontent.com/3245109/223341619-d67056f2-0420-4272-8d4d-79814da8e42e.png)

**Comment by joycarpediem** [comment]
@wayangalihpratama 
- Use the computed validation questionnaire 
- add the cascade but do not add anything under section 3
- submit--> validation popup shown
- fix the validation error AND delete the cascade
Issue : Submission proceeds

**Comment by wayangalihpratama** [comment]
Hi @joycarpediem , 
That issue will be fixed on the incoming ARF version update for ISCO.
