### ISSUE TITLE
Zero not being captured in the number field 

### ISSUE THREAD

**Issue by joycarpediem** [akvo/isco#321]
https://www.loom.com/share/48b015c9fbc34724b02c0e48f138fbe6

**Comment by joycarpediem** [comment]
@wayangalihpratama cannot submit response without answering all mandatory questions 

https://www.loom.com/share/d751e62d6b0943dc83502396d04394d6

**Comment by wayangalihpratama** [comment]
**Todo**
- [ ] Look into submit button action, submit with warning modal then test with normal questionnaire without computed validation or core mandatory value
