### ISSUE TITLE
Add "Status: Saved" 

### ISSUE THREAD

**Issue by joycarpediem** [akvo/isco#360]
to the survey title in the PDF  (right aligned)

**Comment by joycarpediem** [comment]
@navins94 , where am i supposed to see this ?
I tried for one saved survey in test and i do not see it 


![Image](https://user-images.githubusercontent.com/4419787/222970348-c28de4fe-5a89-45d3-af2a-f0ba1564ec20.png)

**Comment by navins94** [comment]
We need to create new survey. I think it will not be available to old one as the file would have been generated earlier
![Screenshot 2023-03-05 at 9 10 21 PM](https://user-images.githubusercontent.com/24510012/222970497-a0eb1f88-6a9d-4685-87e0-5b8ce2879567.png)

**Comment by navins94** [comment]
Or I am not sure if the latest changes have been pushed to the env we are using

**Comment by dedenbangkit** [comment]
@wayangalihpratama @navins94 when we click download request, are we generating a new file or we re-use the one that is already generated?

**Comment by navins94** [comment]
re-use the one already generated

**Comment by dedenbangkit** [comment]
@navins94 and what happens if I edit the saved one. Will it regenerated?

**Comment by navins94** [comment]
Once we edit something we make call to `download/new` endpoint which generate the report again

**Comment by joycarpediem** [comment]
@navins94 , so what will happen in the following workflow

User creates a new data point and saves it .
Then the user requests for download 
Then the user makes some more edits to the data point 
Do they have to request for download again ?

**Comment by navins94** [comment]
Yes they have to make download request again. Once we edit something then in download page we get request button again for that particular survey.

**Comment by dedenbangkit** [comment]
@navins94 I don't see re-request button (or button goes back to request)

**Comment by navins94** [comment]
Okay so when we update the data from this dropdown then we get request button again. But if we edit previously saved from then we do not get the request button
![Screenshot 2023-03-07 at 12 49 19 PM](https://user-images.githubusercontent.com/24510012/223351844-695e9fbc-38b7-46f4-9d40-c0df16942c1a.png)

**Comment by dedenbangkit** [comment]
@navins94 
https://user-images.githubusercontent.com/3245109/223353972-42c34ca5-0a0e-4551-8ae4-b058fd3162b9.mp4

**Comment by navins94** [comment]
I think there is some bug with how the request button appears. If we saved the survey from start filling new form dropdown then it appears but if saved again from previously saved form then it does not appear. I am looking into it

**Comment by wayangalihpratama** [comment]
Hi, the Request button will automatically appear after the Download request expired time.
That's the condition from the beginning we implement Dowload - Request button.
Do we need to change Download button to Request directly after the submission is updated?

**Comment by dedenbangkit** [comment]
Yes, I've tried to submit the draft (saved survey) which has been generated. However, the download button still appear even the status is changed.

**Comment by navins94** [comment]
Add requested by and requested date below saved status.
Change saved status text to draft

**Comment by wayangalihpratama** [comment]
When submission saved/submitted, all download request by that user (who saved the submission) should be deleted from download table. (only for saved submission)
