### ISSUE TITLE
mask survey editor when loading

### ISSUE THREAD

**Issue by joycarpediem** [akvo/isco#362]
Issue 
Currently for large surveys the survey editor takes a while to load . During the loading the user is presented with an empty survey editor . It also allows one to enter values in the fields . There is no feedback to the user that something is happening 

Explore the something like https://www.npmjs.com/package/react-loading-skeleton
Discuss effort and alternatives with @joycarpediem before implementing

**Comment by wayangalihpratama** [comment]
https://user-images.githubusercontent.com/49269977/222324408-1f1ffba0-47da-4c04-8a95-528d9671f145.mp4

Hi @joycarpediem , do you want something like the above recording?

**Comment by joycarpediem** [comment]
@wayangalihpratama , ya bagus mas
